'use strict';

/**
 * Takes raw chart data from the API and builds a markdown health report.
 */
function buildReport(charts) {
  const lines = [];
  const now = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  lines.push(`# RevenueCat Business Health Report`);
  lines.push(`_Generated on ${now}_\n`);
  lines.push('---\n');

  // MRR section
  if (charts.mrr) {
    const { summary, values } = charts.mrr;
    const avg = summary?.average?.MRR ?? 0;
    const latestMRR = lastComplete(values)?.value ?? 0;
    const earliestMRR = firstComplete(values)?.value ?? 0;
    const mrrGrowth = earliestMRR > 0
      ? (((latestMRR - earliestMRR) / earliestMRR) * 100).toFixed(1)
      : 'N/A';

    lines.push('## Monthly Recurring Revenue (MRR)');
    lines.push(`| Metric | Value |`);
    lines.push(`|--------|-------|`);
    lines.push(`| Current MRR | **${fmt$(latestMRR)}** |`);
    lines.push(`| Average MRR (period) | ${fmt$(avg)} |`);
    lines.push(`| Growth over period | ${mrrGrowth}% |`);
    lines.push('');
    lines.push(sparkline('MRR trend', values));
    lines.push('');
    lines.push(mrrGrowth !== 'N/A' && parseFloat(mrrGrowth) > 0
      ? `> **Insight:** MRR grew ${mrrGrowth}% over the period — healthy upward momentum.`
      : `> **Insight:** MRR is flat or declining. Review churn and new subscriber acquisition.`);
    lines.push('');
  }

  // Revenue section
  if (charts.revenue) {
    const { summary } = charts.revenue;
    const totalRevenue = summary?.total?.Revenue ?? 0;
    const avgWeekly = summary?.average?.Revenue ?? 0;
    const avgTransactions = summary?.average?.Transactions ?? 0;

    lines.push('## Revenue');
    lines.push(`| Metric | Value |`);
    lines.push(`|--------|-------|`);
    lines.push(`| Total Revenue (period) | **${fmt$(totalRevenue)}** |`);
    lines.push(`| Avg Weekly Revenue | ${fmt$(avgWeekly)} |`);
    lines.push(`| Avg Weekly Transactions | ${Math.round(avgTransactions)} |`);
    lines.push('');

    const arpu = avgTransactions > 0
      ? (avgWeekly / avgTransactions).toFixed(2)
      : 'N/A';
    lines.push(`> **Insight:** Average revenue per transaction is **$${arpu}**. ${
      parseFloat(arpu) > 5
        ? 'Strong ARPU suggests effective pricing or annual plan adoption.'
        : 'Consider promoting annual plans to increase ARPU.'
    }`);
    lines.push('');
  }

  // Active Subscriptions
  if (charts.actives) {
    const { summary, values } = charts.actives;
    const avg = summary?.average?.Actives ?? 0;
    const latest = lastComplete(values)?.value ?? 0;
    const earliest = firstComplete(values)?.value ?? 0;
    const growth = earliest > 0
      ? (((latest - earliest) / earliest) * 100).toFixed(1)
      : 'N/A';

    lines.push('## Active Subscriptions');
    lines.push(`| Metric | Value |`);
    lines.push(`|--------|-------|`);
    lines.push(`| Current Actives | **${Math.round(latest).toLocaleString()}** |`);
    lines.push(`| Average Actives (period) | ${Math.round(avg).toLocaleString()} |`);
    lines.push(`| Growth over period | ${growth}% |`);
    lines.push('');
    lines.push(sparkline('Actives trend', values));
    lines.push('');
  }

  // Churn section
  if (charts.churn) {
    const { summary } = charts.churn;
    const avgChurn = summary?.average?.['Churn Rate'] ?? 0;
    const avgActives = summary?.average?.Actives ?? 0;
    const avgChurned = summary?.average?.['Churned Actives'] ?? 0;

    lines.push('## Churn');
    lines.push(`| Metric | Value |`);
    lines.push(`|--------|-------|`);
    lines.push(`| Avg Weekly Churn Rate | **${avgChurn.toFixed(2)}%** |`);
    lines.push(`| Avg Weekly Actives | ${Math.round(avgActives).toLocaleString()} |`);
    lines.push(`| Avg Weekly Churned | ${Math.round(avgChurned)} |`);
    lines.push('');

    const health = avgChurn < 1
      ? 'Excellent — below 1% weekly churn is top-tier for mobile apps.'
      : avgChurn < 2
      ? 'Good — 1–2% weekly churn is typical for mobile subscription apps.'
      : avgChurn < 4
      ? 'Watch — above 2% warrants investigation into cancellation reasons.'
      : 'Critical — above 4% weekly churn will erode your subscriber base quickly.';
    lines.push(`> **Insight:** ${health}`);
    lines.push('');
  }

  // Trials
  if (charts.trials) {
    const { summary } = charts.trials;
    const avgTrials = summary?.average?.['Active Trials'] ?? summary?.average?.Trials ?? 0;

    if (avgTrials > 0) {
      lines.push('## Trials');
      lines.push(`| Metric | Value |`);
      lines.push(`|--------|-------|`);
      lines.push(`| Avg Active Trials (period) | **${Math.round(avgTrials).toLocaleString()}** |`);
      lines.push('');
    }
  }

  // Recommendations
  lines.push('---');
  lines.push('## Strategic Recommendations');
  lines.push('');
  lines.push(buildRecommendations(charts));
  lines.push('');
  lines.push('---');
  lines.push('_Report generated by [rc-insights](https://github.com/CodeKage25/rc-insights) — a RevenueCat Charts API tool._');

  return lines.join('\n');
}

// ── helpers ────────────────────────────────────────────────────────────────

function fmt$(n) {
  return `$${Number(n).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function lastComplete(values = []) {
  const complete = values.filter((v) => v.measure === 0 && !v.incomplete);
  return complete[complete.length - 1] ?? null;
}

function firstComplete(values = []) {
  return values.find((v) => v.measure === 0 && !v.incomplete) ?? null;
}

/** Build a minimal ASCII sparkline from weekly values */
function sparkline(label, values = []) {
  const pts = values
    .filter((v) => v.measure === 0 && !v.incomplete)
    .map((v) => v.value)
    .slice(-20); // last 20 weeks

  if (pts.length === 0) return '';

  const min = Math.min(...pts);
  const max = Math.max(...pts);
  const range = max - min || 1;
  const bars = ['▁', '▂', '▃', '▄', '▅', '▆', '▇', '█'];

  const line = pts
    .map((v) => bars[Math.round(((v - min) / range) * (bars.length - 1))])
    .join('');

  return `\`${label}: ${line}\` _(last ${pts.length} weeks)_`;
}

function buildRecommendations(charts) {
  const recs = [];

  const churnAvg = charts.churn?.summary?.average?.['Churn Rate'] ?? 0;
  const mrrValues = charts.mrr?.values ?? [];
  const latestMRR = lastComplete(mrrValues)?.value ?? 0;
  const earliestMRR = firstComplete(mrrValues)?.value ?? 0;
  const mrrGrowth = earliestMRR > 0 ? ((latestMRR - earliestMRR) / earliestMRR) * 100 : 0;

  if (churnAvg > 2) {
    recs.push('1. **Reduce churn** — Churn is above healthy thresholds. Survey cancelled users, add an in-app offboarding flow to understand cancellation reasons, and consider a pause/snooze subscription option.');
  } else {
    recs.push('1. **Maintain low churn** — Your churn rate is healthy. Focus on keeping product quality high and iterate on features that drive daily habit formation.');
  }

  if (mrrGrowth < 5) {
    recs.push('2. **Boost acquisition** — MRR growth is slow. Experiment with App Store Optimization (ASO), Apple Search Ads, and referral mechanics to increase new trial starts.');
  } else {
    recs.push('2. **Double down on what\'s working** — MRR growth is positive. Identify your top acquisition channels using RevenueCat\'s `first_platform` and `store` segments and scale them.');
  }

  recs.push('3. **Test annual plan pricing** — Annual subscriptions improve LTV and reduce churn by 12x compared to monthly. Use RevenueCat Experiments to A/B test an annual upsell paywall.');
  recs.push('4. **Segment by country** — Use the `first_country` filter in the Charts API to identify your highest-LTV markets and consider localized pricing via RevenueCat\'s price experiments.');
  recs.push('5. **Monitor MRR movement weekly** — Set up the `mrr_movement` chart to track New MRR vs. Churned MRR each week. When churned MRR exceeds new MRR, act immediately.');

  return recs.join('\n');
}

module.exports = { buildReport };
